//! Writes to the `songs` table.

use sqlx_core::query_builder::QueryBuilder;
use sqlx_postgres::{PgPool, Postgres};

/// A song to record, as the source described it.
///
/// The key columns are not here: `artist_key` and `title_key` are generated by
/// the database from `artist` and `title`, so there is one normalization rule
/// and it lives in the schema.
#[derive(Debug)]
pub struct NewSong {
    /// The lead artist. This, normalized, is half of the song's identity.
    pub artist: String,
    pub title: String,
    /// Every credited artist in the source's order, `artist` included.
    pub artists: Vec<String>,
    pub album: Option<String>,
    /// Free text, not a date: Spotify's precision varies by release.
    pub album_release_date: Option<String>,
    /// Postgres has no unsigned integers; the caller narrows to `i64`.
    pub duration_ms: Option<i64>,
    pub spotify_id: Option<String>,
    pub isrc: Option<String>,
}

/// Insert songs, leaving any already-recorded song exactly as it is.
///
/// Returns how many rows were new. Duplicates *within* `songs` are handled by
/// the same `DO NOTHING`, so the caller does not have to pre-deduplicate (and
/// so does not have to reimplement the database's normalization to do it).
#[tracing::instrument(
    name = "INSERT songs",
    skip_all,
    fields(
        otel.kind = "client",
        db.system.name = "postgresql",
        db.operation.name = "INSERT",
        db.collection.name = "songs",
        db.response.returned_rows = tracing::field::Empty,
    ),
    err,
)]
pub async fn insert_songs(pool: &PgPool, songs: &[NewSong]) -> anyhow::Result<u64> {
    if songs.is_empty() {
        return Ok(0);
    }

    let mut query: QueryBuilder<Postgres> = QueryBuilder::new(
        "INSERT INTO songs \
         (artist, title, artists, album, album_release_date, duration_ms, spotify_id, isrc) ",
    );
    query.push_values(songs, |mut row, song| {
        row.push_bind(&song.artist)
            .push_bind(&song.title)
            .push_bind(&song.artists)
            .push_bind(&song.album)
            .push_bind(&song.album_release_date)
            .push_bind(song.duration_ms)
            .push_bind(&song.spotify_id)
            .push_bind(&song.isrc);
    });
    // Named rather than inferred, so the statement fails loudly if the
    // constraint is ever renamed out from under it.
    query.push(" ON CONFLICT ON CONSTRAINT songs_artist_title_key DO NOTHING");

    let inserted = query.build().execute(pool).await?.rows_affected();
    tracing::Span::current().record("db.response.returned_rows", inserted);
    Ok(inserted)
}
